[package]
name = "os"
version = "0.1.0"
authors = ["root"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]

# panic 时直接终止，避免堆栈展开
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
